CREATE DATABASE IF NOT EXISTS sampledb CHARACTER SET utf8 COLLATE utf8_bin;

CREATE USER 'sampleuser'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON sampledb.* TO 'sampleuser'@'%';
FLUSH PRIVILEGES;
