CREATE TABLE IF NOT EXISTS sampledb.hoge (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(10),
    first_name VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_bin;

CREATE TABLE IF NOT EXISTS sampledb.fuga (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    hoge VARCHAR(10),
    fuga VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_bin;
